services:
  video480:
    labels:
      dev.okteto.com/public: "true"
    build:
      dockerfile: Dockerfile01 
    deploy:
      mode: global
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
    restart: on-failure    
    ports:
      - 8080:8080  
  video576:
    labels:
      dev.okteto.com/public: "true" 
    build:
      dockerfile: Dockerfile02  
    deploy:
      mode: global
      replicas: 1
    restart: on-failure    
    ports:
      - 8080:8080
