services:
  video480:
    labels:
      dev.okteto.com/public: "true"
    build:
      dockerfile: Dockerfile01
    deploy:
      mode: global
      replicas: 1  
    ports:
      - 8080:8080   
  video576:
    labels:
      dev.okteto.com/public: "true"
    deploy:
      mode: global
      replicas: 1 
    build:
      dockerfile: Dockerfile02
    ports:
      - 8080:8080
    environment:
      API_ID: 4627680  
      API_HASH: be174323fb7b611dbc180526a69743ef
      BOT_TOKEN: 5240703455:AAE-K1y0b-jTzM7LLh21fHxKQaHzPq3-q24
      SUDO_USERS: 627191784
      DOWNLOAD_DIR: VideoEncoder/utils/downloads/
