services:
  audio:
    labels:
      dev.okteto.com/public: "true"
    build:
      dockerfile: Dockerfile01
    ports:
      - 8080:8080
    environment:
      API_ID: 4627680  
      API_HASH: be174323fb7b611dbc180526a69743ef
      BOT_TOKEN: 5170268091:AAHr8Rz_irtfXhGeBmnBOvtSjeUeX4M4uZI
      SUDO_USERS: 627191784
      DOWNLOAD_DIR: /app/VideoEncoder/utils/downloads/
