apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world
    image: liveslak/slackware:base_x64_15.0
    command: ["echo"]
    args: ["hola desde pod"]
    ports:
    - containerPort: 8080
