apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
spec:
  - image: test
    - image: liveslak/slackware:base_x64_15.0
      name: kuard
      command: ["echo"]
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
