apiVersion: v1
kind: Pod
metadata:
  name: "hello-world"
  labels:
    name: "helloApp"
  
spec:
  restartPolicy: Never
  containers:
   -
    image: "ubuntu"
    name: "hello"
    ports:
          -
           containerPort: 8020
    env:
        -
          name: "MESSAGE1"
          value: "hello"
        -
          name: "MESSAGE2"
          value: "kubernetes"
    args: ["/bin/echo", " $(MESSAGE1)", " $(MESSAGE2)"]
